// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "ffmpeg_types.h"
#include <Rcpp.h>

using namespace Rcpp;

// list_codecs
Rcpp::DataFrame list_codecs();
RcppExport SEXP _ffmpeg_list_codecs() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(list_codecs());
    return rcpp_result_gen;
END_RCPP
}
// list_formats
Rcpp::DataFrame list_formats();
RcppExport SEXP _ffmpeg_list_formats() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(list_formats());
    return rcpp_result_gen;
END_RCPP
}
// new_encoder_internal
XPtrEncoder new_encoder_internal(Rcpp::String path, Rcpp::String codec, size_t width, size_t height, size_t fps);
RcppExport SEXP _ffmpeg_new_encoder_internal(SEXP pathSEXP, SEXP codecSEXP, SEXP widthSEXP, SEXP heightSEXP, SEXP fpsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::String >::type path(pathSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type codec(codecSEXP);
    Rcpp::traits::input_parameter< size_t >::type width(widthSEXP);
    Rcpp::traits::input_parameter< size_t >::type height(heightSEXP);
    Rcpp::traits::input_parameter< size_t >::type fps(fpsSEXP);
    rcpp_result_gen = Rcpp::wrap(new_encoder_internal(path, codec, width, height, fps));
    return rcpp_result_gen;
END_RCPP
}
// add_frame_internal
XPtrEncoder add_frame_internal(XPtrEncoder encoder, Rcpp::RawVector image);
RcppExport SEXP _ffmpeg_add_frame_internal(SEXP encoderSEXP, SEXP imageSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtrEncoder >::type encoder(encoderSEXP);
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type image(imageSEXP);
    rcpp_result_gen = Rcpp::wrap(add_frame_internal(encoder, image));
    return rcpp_result_gen;
END_RCPP
}
