# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

list_codecs <- function() {
    .Call('_ffmpeg_list_codecs', PACKAGE = 'ffmpeg')
}

list_formats <- function() {
    .Call('_ffmpeg_list_formats', PACKAGE = 'ffmpeg')
}

new_encoder_internal <- function(path, codec, width, height, fps) {
    .Call('_ffmpeg_new_encoder_internal', PACKAGE = 'ffmpeg', path, codec, width, height, fps)
}

add_frame_internal <- function(encoder, image) {
    .Call('_ffmpeg_add_frame_internal', PACKAGE = 'ffmpeg', encoder, image)
}

